Interview dates endpoint
HKN-UCSD/hkn-server pull request #155
Opened 2020-11-20 06:09 UTC by frankyyzy

#130

2020-11-20 08:39 UTC, godwinpang requested changes

2020-11-20 08:39 UTC, godwinpang commented on src/entities/InductionClass.ts
> +    type: 'simple-json',
we should use json instead of simple-json here to rely on the native json column type

2020-11-20 08:39 UTC, godwinpang commented on src/entities/InductionClass.ts
> +    type: 'simple-json',
might have to do more magic with getting types to work nicely idk

2020-11-20 08:39 UTC, godwinpang commented on src/entities/InductionClass.ts
> +  // e.g. fa20 (lower case to match string in url)
we shouldn't be changing this, existing data is already in upper case

2020-11-21 18:16 UTC, godwinpang requested changes

2020-11-21 18:16 UTC, godwinpang commented on src/payloads/InterviewDates.ts
> +  interview: Date[];
We should try to have payloads as strings - Date gets converted into ISO string in json anyways
Better to be explicit here

2020-12-01 08:39 UTC, thaigillespie commented
Gonna just merge this now

2020-12-01 08:40 UTC, merged