Qr Code Page for Events
HKN-UCSD/hkn-server pull request #265
Opened 2021-08-15 03:38 UTC by Titan-Ngo

Closes #236 

I followed the Qr Code Intermediate page suggestion, which directs users depending on whether they are signed in or not. Thus, two new pages were made: QrCodePage (accessed via a button from the EventDetails page) and QrCodeIntermediatePage (accessed via scanning the QR Code on the QrCodePage). It was unspecified what information to include on the QrCodePage, such I just included most of the Event details included on Event modals.

Below are videos showing the pages:

Signed in placeholder - Event details page.
[QrCode Usage - Signed In User](https://user-images.githubusercontent.com/42155527/129466027-35e6c7ee-ac13-4660-977d-c8f5c1f961fd.mp4
)

Not signed in placeholder - Empty page.
[QrCode Usage - Not Signed In](https://user-images.githubusercontent.com/42155527/129466041-1e8ff23f-1fb1-4792-9a9e-385359a98810.mp4)

[QrCode Scanning - Gives Correct URL](https://user-images.githubusercontent.com/42155527/129466112-6898b516-070e-44a0-957d-2e5b015431d0.mp4)

2021-08-16 06:13 UTC, thaigillespie requested changes
Looks decent so far. I left some comments regarding your code for you to look at

2021-08-16 06:13 UTC, thaigillespie commented on frontend/src/pages/QrCodeIntermediatePage/index.tsx
> +            history.push(ROUTES.EVENT_DETAILS_WITH_ID(eventId));
I think this is fine, especially if QR code will only ever be used for events stuff (it is for now, who knows what will happen in the future).

2021-08-16 07:07 UTC, audreygao commented on frontend/src/pages/QrCodeIntermediatePage/index.tsx
> +          <Grid container direction='column'>
I was reading through #236, if the user is not logged in, I think it should redirect to the inductee/guest page I worked on? 'events/id/signinoptions'

2021-08-16 07:13 UTC, thaigillespie commented on frontend/src/pages/QrCodeIntermediatePage/index.tsx
> +          <Grid container direction='column'>
Yes, you're right. Good catch. Alright just do what Audrey said here @Titan-Ngo

2021-08-22 10:06 UTC, Titan-Ngo commented
- redirected user to  'events/id/signinoptions' when not signed in 
- replaced usage of Location State to using eventId (passed as a route param) to get event info

2021-08-22 17:57 UTC, thaigillespie approved these changes
Lgtm. Good job!

2021-08-23 07:37 UTC, audreygao approved these changes
looks good to me

2021-08-23 07:50 UTC, merged