Add event signin button feedback
HKN-UCSD/hkn-server pull request #314
Opened 2022-04-13 01:20 UTC by audreygao

2022-04-13 01:27 UTC, audreygao commented
<img width="1440" alt="Screen Shot 2022-04-12 at 6 26 36 PM" src="https://user-images.githubusercontent.com/57417548/163080898-69b198e7-dc48-45bc-96c2-c148715a6ba2.png">
<img width="1440" alt="Screen Shot 2022-04-12 at 6 26 50 PM" src="https://user-images.githubusercontent.com/57417548/163080905-a51a7380-4b9a-4970-8761-e22ee5e7122c.png">

2022-04-15 22:48 UTC, godwinpang requested changes

2022-04-15 22:48 UTC, godwinpang commented on backend/src/controllers/EventController.ts
> +  async affiliateEventSigninResult(
would be good to name functions as verbs, looks like this gets the attendance for an affiliate event?

```suggestion
  async getAffiliateEventAttendance
```

2022-04-15 22:48 UTC, godwinpang commented on backend/src/payloads/Attendance.ts
> +  signin: boolean;
```suggestion
  isSignedIn: boolean;
```

2022-04-15 22:48 UTC, godwinpang commented on frontend/src/pages/EventDetailsPage/components/EventDetails/index.tsx
> +import { affiliateSignInToEventResult } from '@Services/EventService';
can consolidate with above import

2022-04-15 22:48 UTC, godwinpang commented on frontend/src/pages/EventDetailsPage/components/EventDetails/index.tsx
> +  const [result, setResult] = useState<boolean>(false);
nit: 
```suggestion
  const [isSignedIn, setIsSignedIn] = useState<boolean>(false);

```

2022-04-15 22:48 UTC, godwinpang commented on frontend/src/pages/EventDetailsPage/components/buttons/SignInButton.ts
> +  }
```suggestion
  const buttonProps = signedIn ? {children: 'Signed In', disabled: true} : {children: 'Sign In'}
  return InducteeRenderPermission(Button)({
    ...buttonProps,
    primary: true,
    positive: true,
    onClick: () => {
      try {
        affiliateSignInToEvent(eventId);
        alert("You've successfully signed in!");
      } catch {
        alert('Your sign in request could not be processed.');
      }
    },
  });
```

2022-04-20 01:09 UTC, laurenkiyomi submitted a review, later dismissed

2022-04-20 01:34 UTC, audreygao commented on backend/src/payloads/Attendance.ts
> +  signin: boolean;
updated

2022-04-26 23:07 UTC, godwinpang approved these changes
thanks for the changes

2022-04-26 23:07 UTC, godwinpang commented on frontend/src/pages/EventDetailsPage/components/buttons/SignInButton.ts
> +
nit: it's good practice to eliminate the number of unnecessary changes to make code review easier
no need to change - just a small thing

2022-04-29 00:17 UTC, merged