Test signup
HKN-UCSD/hkn-server pull request #97
Opened 2020-09-07 23:44 UTC by godwinpang

2020-09-08 20:26 UTC, thaigillespie approved these changes
Lgtm

2020-09-08 20:26 UTC, thaigillespie commented on src/tests/AuthController.test.ts
> +    (AppUserServiceImpl.isGuest as jest.Mock).mockImplementation(() => undefined);
Should return true

2020-09-09 19:09 UTC, thaigillespie requested changes

2020-09-09 19:09 UTC, thaigillespie commented on src/tests/AuthController.test.ts
> +    (AppUserServiceImpl.isGuest as jest.Mock).mockImplementation(() => false);
Shouldn't this be true and not false?

2020-09-09 19:31 UTC, godwinpang commented
Yeah i suck 

Sent from my iPhone

> On 9 Sep 2020, at 12:09, Thai <notifications@github.com> wrote:
> 
> @thaigillespie requested changes on this pull request.
> 
> In src/tests/AuthController.test.ts:
> 
> > +});
> +
> +afterEach(() => {
> +  jest.clearAllMocks();
> +});
> +
> +describe('signUpUser', () => {
> +  it('should return undefined on nonpermitted email', async () => {
> +    (AppUserServiceImpl.getAppUserByEmail as jest.Mock).mockImplementation(() => undefined);
> +
> +    expect(await authController.signUpUser(new AppUserSignupRequest())).toEqual(undefined);
> +  });
> +
> +  it('should return undefined for guest', async () => {
> +    (AppUserServiceImpl.getAppUserByEmail as jest.Mock).mockImplementation(() => new AppUser());
> +    (AppUserServiceImpl.isGuest as jest.Mock).mockImplementation(() => false);
> Shouldn't this be true and not false?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-09 19:50 UTC, thaigillespie commented
lmao you're fine

2020-09-09 22:19 UTC, thaigillespie approved these changes

2020-09-10 08:02 UTC, merged